const loaderActions = {
	TOGGLE_LOADER: "TOGGLE_LOADER",
	SET_LOADER_TYPE: "SET_LOADER_TYPE",
	ADD_LOADED_ROUTE: "ADD_LOADED_ROUTE",
	UPDATE_ENTRY_ANIM_DURATION: "UPDATE_ENTRY_ANIM_DURATION",
	UPDATE_EXIT_ANIM_DURATION: "UPDATE_EXIT_ANIM_DURATION",
};

export default loaderActions;
