const UI = {
	TOGGLE_MENU: 'TOGGLE_MENU',
	SET_SCROLLBAR: 'SET_SCROLLBAR',
	SET_SCROLLBAR_OVERSCROLL_LISTENER: 'SET_SCROLLBAR_OVERSCROLL_LISTENER',
	FLUSH_SCROLLBAR_OVERSCROLL_LISTENER: 'FLUSH_SCROLLBAR_OVERSCROLL_LISTENER'
};

export default UI;
