const UI = {
	TOGGLE_MENU: "TOGGLE_MENU",
	TURN_POINTER_INTO_BUTTON: "TURN_POINTER_INTO_BUTTON",
	TURN_POINTER_INTO_BULLET: "TURN_POINTER_INTO_BULLET",
	TOGGLE_FOLLOWER: "TOGGLE_FOLLOWER",
	UPDATE_CURSOR_POSITION: "UPDATE_CURSOR_POSITION",
	SET_VISIBILITY: "SET_VISIBILITY",
};

export default UI;
